baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hugo-book"


[params]
  BookSection = 'docs'
  BookTheme = 'auto'
  BookToC = true
  BookSearch = true
  type = 'docs'